package model;
// Generated Apr 3, 2012 7:10:18 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Answers generated by hbm2java
 */
public class Answers  implements java.io.Serializable {


     private Long ansId;
     private User user;
     private Questions questions;
     private String answer;
     private String status;
     private Date ansTime;

    public Answers() {
    }

    public Answers(User user, Questions questions, String answer, String status, Date ansTime) {
       this.user = user;
       this.questions = questions;
       this.answer = answer;
       this.status = status;
       this.ansTime = ansTime;
    }
   
    public Long getAnsId() {
        return this.ansId;
    }
    
    public void setAnsId(Long ansId) {
        this.ansId = ansId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Questions getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Questions questions) {
        this.questions = questions;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getAnsTime() {
        return this.ansTime;
    }
    
    public void setAnsTime(Date ansTime) {
        this.ansTime = ansTime;
    }




}


