package model;
// Generated Apr 3, 2012 7:10:18 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Bookmarks generated by hbm2java
 */
public class Bookmarks  implements java.io.Serializable {


     private Long bookmarkId;
     private User user;
     private String bookmarkName;
     private String bookmarkUrl;
     private String bookmarkCategory;
     private Date bookmarkCreatetime;
     private String notes;
     private String status;

    public Bookmarks() {
    }

	
    public Bookmarks(User user, String bookmarkUrl, Date bookmarkCreatetime, String status) {
        this.user = user;
        this.bookmarkUrl = bookmarkUrl;
        this.bookmarkCreatetime = bookmarkCreatetime;
        this.status = status;
    }
    public Bookmarks(User user, String bookmarkName, String bookmarkUrl, String bookmarkCategory, Date bookmarkCreatetime, String notes, String status) {
       this.user = user;
       this.bookmarkName = bookmarkName;
       this.bookmarkUrl = bookmarkUrl;
       this.bookmarkCategory = bookmarkCategory;
       this.bookmarkCreatetime = bookmarkCreatetime;
       this.notes = notes;
       this.status = status;
    }
   
    public Long getBookmarkId() {
        return this.bookmarkId;
    }
    
    public void setBookmarkId(Long bookmarkId) {
        this.bookmarkId = bookmarkId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getBookmarkName() {
        return this.bookmarkName;
    }
    
    public void setBookmarkName(String bookmarkName) {
        this.bookmarkName = bookmarkName;
    }
    public String getBookmarkUrl() {
        return this.bookmarkUrl;
    }
    
    public void setBookmarkUrl(String bookmarkUrl) {
        this.bookmarkUrl = bookmarkUrl;
    }
    public String getBookmarkCategory() {
        return this.bookmarkCategory;
    }
    
    public void setBookmarkCategory(String bookmarkCategory) {
        this.bookmarkCategory = bookmarkCategory;
    }
    public Date getBookmarkCreatetime() {
        return this.bookmarkCreatetime;
    }
    
    public void setBookmarkCreatetime(Date bookmarkCreatetime) {
        this.bookmarkCreatetime = bookmarkCreatetime;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


