package model;
// Generated Apr 3, 2012 7:10:18 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Ideas generated by hbm2java
 */
public class Ideas  implements java.io.Serializable {


     private Long ideaId;
     private User user;
     private String ideas;
     private Date createTime;
     private String status;

    public Ideas() {
    }

    public Ideas(User user, String ideas, Date createTime, String status) {
       this.user = user;
       this.ideas = ideas;
       this.createTime = createTime;
       this.status = status;
    }
   
    public Long getIdeaId() {
        return this.ideaId;
    }
    
    public void setIdeaId(Long ideaId) {
        this.ideaId = ideaId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getIdeas() {
        return this.ideas;
    }
    
    public void setIdeas(String ideas) {
        this.ideas = ideas;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


