package model;
// Generated Apr 3, 2012 7:10:18 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Scribbles generated by hbm2java
 */
public class Scribbles  implements java.io.Serializable {


     private Long scribbleId;
     private User user;
     private String scribbleDesc;
     private String scribbleType;
     private String status;
     private Date scribbleTime;
     private Set<ScribbleReply> scribbleReplies = new HashSet<ScribbleReply>(0);
     private Set<ScribbleForward> scribbleForwards = new HashSet<ScribbleForward>(0);

    public Scribbles() {
    }

	
    public Scribbles(User user, String scribbleDesc, String scribbleType, String status, Date scribbleTime) {
        this.user = user;
        this.scribbleDesc = scribbleDesc;
        this.scribbleType = scribbleType;
        this.status = status;
        this.scribbleTime = scribbleTime;
    }
    public Scribbles(User user, String scribbleDesc, String scribbleType, String status, Date scribbleTime, Set<ScribbleReply> scribbleReplies, Set<ScribbleForward> scribbleForwards) {
       this.user = user;
       this.scribbleDesc = scribbleDesc;
       this.scribbleType = scribbleType;
       this.status = status;
       this.scribbleTime = scribbleTime;
       this.scribbleReplies = scribbleReplies;
       this.scribbleForwards = scribbleForwards;
    }
   
    public Long getScribbleId() {
        return this.scribbleId;
    }
    
    public void setScribbleId(Long scribbleId) {
        this.scribbleId = scribbleId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getScribbleDesc() {
        return this.scribbleDesc;
    }
    
    public void setScribbleDesc(String scribbleDesc) {
        this.scribbleDesc = scribbleDesc;
    }
    public String getScribbleType() {
        return this.scribbleType;
    }
    
    public void setScribbleType(String scribbleType) {
        this.scribbleType = scribbleType;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getScribbleTime() {
        return this.scribbleTime;
    }
    
    public void setScribbleTime(Date scribbleTime) {
        this.scribbleTime = scribbleTime;
    }
    public Set<ScribbleReply> getScribbleReplies() {
        return this.scribbleReplies;
    }
    
    public void setScribbleReplies(Set<ScribbleReply> scribbleReplies) {
        this.scribbleReplies = scribbleReplies;
    }
    public Set<ScribbleForward> getScribbleForwards() {
        return this.scribbleForwards;
    }
    
    public void setScribbleForwards(Set<ScribbleForward> scribbleForwards) {
        this.scribbleForwards = scribbleForwards;
    }




}


