package model;
// Generated Apr 3, 2012 7:10:18 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ScribbleReply generated by hbm2java
 */
public class ScribbleReply  implements java.io.Serializable {


     private Long replyId;
     private User user;
     private Scribbles scribbles;
     private String replyDesc;
     private Date replyTime;

    public ScribbleReply() {
    }

    public ScribbleReply(User user, Scribbles scribbles, String replyDesc, Date replyTime) {
       this.user = user;
       this.scribbles = scribbles;
       this.replyDesc = replyDesc;
       this.replyTime = replyTime;
    }
   
    public Long getReplyId() {
        return this.replyId;
    }
    
    public void setReplyId(Long replyId) {
        this.replyId = replyId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Scribbles getScribbles() {
        return this.scribbles;
    }
    
    public void setScribbles(Scribbles scribbles) {
        this.scribbles = scribbles;
    }
    public String getReplyDesc() {
        return this.replyDesc;
    }
    
    public void setReplyDesc(String replyDesc) {
        this.replyDesc = replyDesc;
    }
    public Date getReplyTime() {
        return this.replyTime;
    }
    
    public void setReplyTime(Date replyTime) {
        this.replyTime = replyTime;
    }




}


