package model;
// Generated Mar 29, 2012 7:55:39 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Long userId;
     private String emailId;
     private String password;
     private String userName;
     private Date regDate;
     private String userStatus;
     private long confirmCode;
     private Set<Bookmarks> bookmarkses = new HashSet<Bookmarks>(0);
     private Set<Userfeed> userfeeds = new HashSet<Userfeed>(0);
     private Set<UserDetails> userDetailses = new HashSet<UserDetails>(0);

    public User() {
    }

	
    public User(String emailId, String password, String userName, String userStatus, long confirmCode) {
        this.emailId = emailId;
        this.password = password;
        this.userName = userName;
        this.userStatus = userStatus;
        this.confirmCode = confirmCode;
    }
    public User(String emailId, String password, String userName, Date regDate, String userStatus, long confirmCode, Set<Bookmarks> bookmarkses, Set<Userfeed> userfeeds, Set<UserDetails> userDetailses) {
       this.emailId = emailId;
       this.password = password;
       this.userName = userName;
       this.regDate = regDate;
       this.userStatus = userStatus;
       this.confirmCode = confirmCode;
       this.bookmarkses = bookmarkses;
       this.userfeeds = userfeeds;
       this.userDetailses = userDetailses;
    }
   
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }
    public String getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus;
    }
    public long getConfirmCode() {
        return this.confirmCode;
    }
    
    public void setConfirmCode(long confirmCode) {
        this.confirmCode = confirmCode;
    }
    public Set<Bookmarks> getBookmarkses() {
        return this.bookmarkses;
    }
    
    public void setBookmarkses(Set<Bookmarks> bookmarkses) {
        this.bookmarkses = bookmarkses;
    }
    public Set<Userfeed> getUserfeeds() {
        return this.userfeeds;
    }
    
    public void setUserfeeds(Set<Userfeed> userfeeds) {
        this.userfeeds = userfeeds;
    }
    public Set<UserDetails> getUserDetailses() {
        return this.userDetailses;
    }
    
    public void setUserDetailses(Set<UserDetails> userDetailses) {
        this.userDetailses = userDetailses;
    }




}


