package model;
// Generated Mar 29, 2012 7:55:39 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Userfeed generated by hbm2java
 */
public class Userfeed  implements java.io.Serializable {


     private Long feedId;
     private User user;
     private String feedDesc;
     private Date feedTime;
     private String feedType;

    public Userfeed() {
    }

    public Userfeed(User user, String feedDesc, Date feedTime, String feedType) {
       this.user = user;
       this.feedDesc = feedDesc;
       this.feedTime = feedTime;
       this.feedType = feedType;
    }
   
    public Long getFeedId() {
        return this.feedId;
    }
    
    public void setFeedId(Long feedId) {
        this.feedId = feedId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getFeedDesc() {
        return this.feedDesc;
    }
    
    public void setFeedDesc(String feedDesc) {
        this.feedDesc = feedDesc;
    }
    public Date getFeedTime() {
        return this.feedTime;
    }
    
    public void setFeedTime(Date feedTime) {
        this.feedTime = feedTime;
    }
    public String getFeedType() {
        return this.feedType;
    }
    
    public void setFeedType(String feedType) {
        this.feedType = feedType;
    }




}


