package model;
// Generated Mar 29, 2012 7:55:39 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * UserDetails generated by hbm2java
 */
public class UserDetails  implements java.io.Serializable {


     private long userId;
     private User user;
     private String firestName;
     private String lastName;
     private String gender;
     private Date dob;
     private String city;
     private String stateReg;
     private String country;
     private String postalZip;
     private Date lastUpdate;

    public UserDetails() {
    }

	
    public UserDetails(long userId, User user) {
        this.userId = userId;
        this.user = user;
    }
    public UserDetails(long userId, User user, String firestName, String lastName, String gender, Date dob, String city, String stateReg, String country, String postalZip, Date lastUpdate) {
       this.userId = userId;
       this.user = user;
       this.firestName = firestName;
       this.lastName = lastName;
       this.gender = gender;
       this.dob = dob;
       this.city = city;
       this.stateReg = stateReg;
       this.country = country;
       this.postalZip = postalZip;
       this.lastUpdate = lastUpdate;
    }
   
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getFirestName() {
        return this.firestName;
    }
    
    public void setFirestName(String firestName) {
        this.firestName = firestName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getStateReg() {
        return this.stateReg;
    }
    
    public void setStateReg(String stateReg) {
        this.stateReg = stateReg;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getPostalZip() {
        return this.postalZip;
    }
    
    public void setPostalZip(String postalZip) {
        this.postalZip = postalZip;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


