package model;
// Generated Apr 3, 2012 7:10:18 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Long userId;
     private String emailId;
     private String password;
     private String userName;
     private Date regDate;
     private String userStatus;
     private long confirmCode;
     private Set<Bookmarks> bookmarkses = new HashSet<Bookmarks>(0);
     private Set<Scribbles> scribbleses = new HashSet<Scribbles>(0);
     private Set<Ideas> ideases = new HashSet<Ideas>(0);
     private Set<ScribbleForward> scribbleForwards = new HashSet<ScribbleForward>(0);
     private Set<Questions> questionses = new HashSet<Questions>(0);
     private Set<Answers> answerses = new HashSet<Answers>(0);
     private Set<UserDetails> userDetailses = new HashSet<UserDetails>(0);
     private Set<ScribbleReply> scribbleReplies = new HashSet<ScribbleReply>(0);

    public User() {
    }

	
    public User(String emailId, String password, String userName, Date regDate, String userStatus, long confirmCode) {
        this.emailId = emailId;
        this.password = password;
        this.userName = userName;
        this.regDate = regDate;
        this.userStatus = userStatus;
        this.confirmCode = confirmCode;
    }
    public User(String emailId, String password, String userName, Date regDate, String userStatus, long confirmCode, Set<Bookmarks> bookmarkses, Set<Scribbles> scribbleses, Set<Ideas> ideases, Set<ScribbleForward> scribbleForwards, Set<Questions> questionses, Set<Answers> answerses, Set<UserDetails> userDetailses, Set<ScribbleReply> scribbleReplies) {
       this.emailId = emailId;
       this.password = password;
       this.userName = userName;
       this.regDate = regDate;
       this.userStatus = userStatus;
       this.confirmCode = confirmCode;
       this.bookmarkses = bookmarkses;
       this.scribbleses = scribbleses;
       this.ideases = ideases;
       this.scribbleForwards = scribbleForwards;
       this.questionses = questionses;
       this.answerses = answerses;
       this.userDetailses = userDetailses;
       this.scribbleReplies = scribbleReplies;
    }
   
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }
    public String getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus;
    }
    public long getConfirmCode() {
        return this.confirmCode;
    }
    
    public void setConfirmCode(long confirmCode) {
        this.confirmCode = confirmCode;
    }
    public Set<Bookmarks> getBookmarkses() {
        return this.bookmarkses;
    }
    
    public void setBookmarkses(Set<Bookmarks> bookmarkses) {
        this.bookmarkses = bookmarkses;
    }
    public Set<Scribbles> getScribbleses() {
        return this.scribbleses;
    }
    
    public void setScribbleses(Set<Scribbles> scribbleses) {
        this.scribbleses = scribbleses;
    }
    public Set<Ideas> getIdeases() {
        return this.ideases;
    }
    
    public void setIdeases(Set<Ideas> ideases) {
        this.ideases = ideases;
    }
    public Set<ScribbleForward> getScribbleForwards() {
        return this.scribbleForwards;
    }
    
    public void setScribbleForwards(Set<ScribbleForward> scribbleForwards) {
        this.scribbleForwards = scribbleForwards;
    }
    public Set<Questions> getQuestionses() {
        return this.questionses;
    }
    
    public void setQuestionses(Set<Questions> questionses) {
        this.questionses = questionses;
    }
    public Set<Answers> getAnswerses() {
        return this.answerses;
    }
    
    public void setAnswerses(Set<Answers> answerses) {
        this.answerses = answerses;
    }
    public Set<UserDetails> getUserDetailses() {
        return this.userDetailses;
    }
    
    public void setUserDetailses(Set<UserDetails> userDetailses) {
        this.userDetailses = userDetailses;
    }
    public Set<ScribbleReply> getScribbleReplies() {
        return this.scribbleReplies;
    }
    
    public void setScribbleReplies(Set<ScribbleReply> scribbleReplies) {
        this.scribbleReplies = scribbleReplies;
    }




}


