package com.model;
// Generated Jul 21, 2012 4:41:27 PM by Hibernate Tools 3.2.1.GA



/**
 * Adminlog generated by hbm2java
 */
public class Adminlog  implements java.io.Serializable {


     private Long AId;
     private String username;
     private String password;

    public Adminlog() {
    }

    public Adminlog(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public Long getAId() {
        return this.AId;
    }
    
    public void setAId(Long AId) {
        this.AId = AId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


