package com.model;
// Generated Jul 21, 2012 4:41:27 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * BusinessValuation generated by hbm2java
 */
public class BusinessValuation  implements java.io.Serializable {


     private Long bvId;
     private String CTitle;
     private String CFirstName;
     private String CSurname;
     private String CCompName;
     private String CHouseNo;
     private String CRoad;
     private String CTown;
     private String CCountry;
     private Long CPostalcode;
     private Long CPhone;
     private Long CWorkPhone;
     private Long CFax;
     private Long CMobile;
     private String CEmail;
     private String BSector;
     private String BTradeType;
     private String BLocaTown;
     private String BLocaCountry;
     private Long BAnnualTurnover;
     private Long BGrossProfit;
     private Long BEmployeesNo;
     private String BTenure;
     private String BWithAccom;
     private Long BRooms;
     private String BFrachises;
     private String BRent;
     private String BRates;
     private String BElectricity;
     private String BOtherExpen;
     private String BComments;
     private Date createddate;

    public BusinessValuation() {
    }

	
    public BusinessValuation(String CTitle, String CFirstName, String CSurname, String CCompName, String CHouseNo, String CRoad, String CTown, String CCountry, String CEmail, String BSector, String BTradeType, String BLocaTown, String BLocaCountry, Date createddate) {
        this.CTitle = CTitle;
        this.CFirstName = CFirstName;
        this.CSurname = CSurname;
        this.CCompName = CCompName;
        this.CHouseNo = CHouseNo;
        this.CRoad = CRoad;
        this.CTown = CTown;
        this.CCountry = CCountry;
        this.CEmail = CEmail;
        this.BSector = BSector;
        this.BTradeType = BTradeType;
        this.BLocaTown = BLocaTown;
        this.BLocaCountry = BLocaCountry;
        this.createddate = createddate;
    }
    public BusinessValuation(String CTitle, String CFirstName, String CSurname, String CCompName, String CHouseNo, String CRoad, String CTown, String CCountry, Long CPostalcode, Long CPhone, Long CWorkPhone, Long CFax, Long CMobile, String CEmail, String BSector, String BTradeType, String BLocaTown, String BLocaCountry, Long BAnnualTurnover, Long BGrossProfit, Long BEmployeesNo, String BTenure, String BWithAccom, Long BRooms, String BFrachises, String BRent, String BRates, String BElectricity, String BOtherExpen, String BComments, Date createddate) {
       this.CTitle = CTitle;
       this.CFirstName = CFirstName;
       this.CSurname = CSurname;
       this.CCompName = CCompName;
       this.CHouseNo = CHouseNo;
       this.CRoad = CRoad;
       this.CTown = CTown;
       this.CCountry = CCountry;
       this.CPostalcode = CPostalcode;
       this.CPhone = CPhone;
       this.CWorkPhone = CWorkPhone;
       this.CFax = CFax;
       this.CMobile = CMobile;
       this.CEmail = CEmail;
       this.BSector = BSector;
       this.BTradeType = BTradeType;
       this.BLocaTown = BLocaTown;
       this.BLocaCountry = BLocaCountry;
       this.BAnnualTurnover = BAnnualTurnover;
       this.BGrossProfit = BGrossProfit;
       this.BEmployeesNo = BEmployeesNo;
       this.BTenure = BTenure;
       this.BWithAccom = BWithAccom;
       this.BRooms = BRooms;
       this.BFrachises = BFrachises;
       this.BRent = BRent;
       this.BRates = BRates;
       this.BElectricity = BElectricity;
       this.BOtherExpen = BOtherExpen;
       this.BComments = BComments;
       this.createddate = createddate;
    }
   
    public Long getBvId() {
        return this.bvId;
    }
    
    public void setBvId(Long bvId) {
        this.bvId = bvId;
    }
    public String getCTitle() {
        return this.CTitle;
    }
    
    public void setCTitle(String CTitle) {
        this.CTitle = CTitle;
    }
    public String getCFirstName() {
        return this.CFirstName;
    }
    
    public void setCFirstName(String CFirstName) {
        this.CFirstName = CFirstName;
    }
    public String getCSurname() {
        return this.CSurname;
    }
    
    public void setCSurname(String CSurname) {
        this.CSurname = CSurname;
    }
    public String getCCompName() {
        return this.CCompName;
    }
    
    public void setCCompName(String CCompName) {
        this.CCompName = CCompName;
    }
    public String getCHouseNo() {
        return this.CHouseNo;
    }
    
    public void setCHouseNo(String CHouseNo) {
        this.CHouseNo = CHouseNo;
    }
    public String getCRoad() {
        return this.CRoad;
    }
    
    public void setCRoad(String CRoad) {
        this.CRoad = CRoad;
    }
    public String getCTown() {
        return this.CTown;
    }
    
    public void setCTown(String CTown) {
        this.CTown = CTown;
    }
    public String getCCountry() {
        return this.CCountry;
    }
    
    public void setCCountry(String CCountry) {
        this.CCountry = CCountry;
    }
    public Long getCPostalcode() {
        return this.CPostalcode;
    }
    
    public void setCPostalcode(Long CPostalcode) {
        this.CPostalcode = CPostalcode;
    }
    public Long getCPhone() {
        return this.CPhone;
    }
    
    public void setCPhone(Long CPhone) {
        this.CPhone = CPhone;
    }
    public Long getCWorkPhone() {
        return this.CWorkPhone;
    }
    
    public void setCWorkPhone(Long CWorkPhone) {
        this.CWorkPhone = CWorkPhone;
    }
    public Long getCFax() {
        return this.CFax;
    }
    
    public void setCFax(Long CFax) {
        this.CFax = CFax;
    }
    public Long getCMobile() {
        return this.CMobile;
    }
    
    public void setCMobile(Long CMobile) {
        this.CMobile = CMobile;
    }
    public String getCEmail() {
        return this.CEmail;
    }
    
    public void setCEmail(String CEmail) {
        this.CEmail = CEmail;
    }
    public String getBSector() {
        return this.BSector;
    }
    
    public void setBSector(String BSector) {
        this.BSector = BSector;
    }
    public String getBTradeType() {
        return this.BTradeType;
    }
    
    public void setBTradeType(String BTradeType) {
        this.BTradeType = BTradeType;
    }
    public String getBLocaTown() {
        return this.BLocaTown;
    }
    
    public void setBLocaTown(String BLocaTown) {
        this.BLocaTown = BLocaTown;
    }
    public String getBLocaCountry() {
        return this.BLocaCountry;
    }
    
    public void setBLocaCountry(String BLocaCountry) {
        this.BLocaCountry = BLocaCountry;
    }
    public Long getBAnnualTurnover() {
        return this.BAnnualTurnover;
    }
    
    public void setBAnnualTurnover(Long BAnnualTurnover) {
        this.BAnnualTurnover = BAnnualTurnover;
    }
    public Long getBGrossProfit() {
        return this.BGrossProfit;
    }
    
    public void setBGrossProfit(Long BGrossProfit) {
        this.BGrossProfit = BGrossProfit;
    }
    public Long getBEmployeesNo() {
        return this.BEmployeesNo;
    }
    
    public void setBEmployeesNo(Long BEmployeesNo) {
        this.BEmployeesNo = BEmployeesNo;
    }
    public String getBTenure() {
        return this.BTenure;
    }
    
    public void setBTenure(String BTenure) {
        this.BTenure = BTenure;
    }
    public String getBWithAccom() {
        return this.BWithAccom;
    }
    
    public void setBWithAccom(String BWithAccom) {
        this.BWithAccom = BWithAccom;
    }
    public Long getBRooms() {
        return this.BRooms;
    }
    
    public void setBRooms(Long BRooms) {
        this.BRooms = BRooms;
    }
    public String getBFrachises() {
        return this.BFrachises;
    }
    
    public void setBFrachises(String BFrachises) {
        this.BFrachises = BFrachises;
    }
    public String getBRent() {
        return this.BRent;
    }
    
    public void setBRent(String BRent) {
        this.BRent = BRent;
    }
    public String getBRates() {
        return this.BRates;
    }
    
    public void setBRates(String BRates) {
        this.BRates = BRates;
    }
    public String getBElectricity() {
        return this.BElectricity;
    }
    
    public void setBElectricity(String BElectricity) {
        this.BElectricity = BElectricity;
    }
    public String getBOtherExpen() {
        return this.BOtherExpen;
    }
    
    public void setBOtherExpen(String BOtherExpen) {
        this.BOtherExpen = BOtherExpen;
    }
    public String getBComments() {
        return this.BComments;
    }
    
    public void setBComments(String BComments) {
        this.BComments = BComments;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }




}


