package com.model;
// Generated Jul 27, 2012 5:21:52 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ContactForSell generated by hbm2java
 */
public class ContactForSell  implements java.io.Serializable {


     private Long RId;
     private String RTitle;
     private String RFirstName;
     private String RSurname;
     private String RCompName;
     private String RCompNo;
     private String RRoad;
     private String RTown;
     private String RCountry;
     private String RPostalCode;
     private Long RPhone;
     private Long RWorkPhone;
     private Long RMobile;
     private Long RFax;
     private String REmail;
     private String RContactOptions;
     private Date RPostTime;

    public ContactForSell() {
    }

	
    public ContactForSell(String RTitle, String RFirstName, String RSurname, String REmail) {
        this.RTitle = RTitle;
        this.RFirstName = RFirstName;
        this.RSurname = RSurname;
        this.REmail = REmail;
    }
    public ContactForSell(String RTitle, String RFirstName, String RSurname, String RCompName, String RCompNo, String RRoad, String RTown, String RCountry, String RPostalCode, Long RPhone, Long RWorkPhone, Long RMobile, Long RFax, String REmail, String RContactOptions, Date RPostTime) {
       this.RTitle = RTitle;
       this.RFirstName = RFirstName;
       this.RSurname = RSurname;
       this.RCompName = RCompName;
       this.RCompNo = RCompNo;
       this.RRoad = RRoad;
       this.RTown = RTown;
       this.RCountry = RCountry;
       this.RPostalCode = RPostalCode;
       this.RPhone = RPhone;
       this.RWorkPhone = RWorkPhone;
       this.RMobile = RMobile;
       this.RFax = RFax;
       this.REmail = REmail;
       this.RContactOptions = RContactOptions;
       this.RPostTime = RPostTime;
    }
   
    public Long getRId() {
        return this.RId;
    }
    
    public void setRId(Long RId) {
        this.RId = RId;
    }
    public String getRTitle() {
        return this.RTitle;
    }
    
    public void setRTitle(String RTitle) {
        this.RTitle = RTitle;
    }
    public String getRFirstName() {
        return this.RFirstName;
    }
    
    public void setRFirstName(String RFirstName) {
        this.RFirstName = RFirstName;
    }
    public String getRSurname() {
        return this.RSurname;
    }
    
    public void setRSurname(String RSurname) {
        this.RSurname = RSurname;
    }
    public String getRCompName() {
        return this.RCompName;
    }
    
    public void setRCompName(String RCompName) {
        this.RCompName = RCompName;
    }
    public String getRCompNo() {
        return this.RCompNo;
    }
    
    public void setRCompNo(String RCompNo) {
        this.RCompNo = RCompNo;
    }
    public String getRRoad() {
        return this.RRoad;
    }
    
    public void setRRoad(String RRoad) {
        this.RRoad = RRoad;
    }
    public String getRTown() {
        return this.RTown;
    }
    
    public void setRTown(String RTown) {
        this.RTown = RTown;
    }
    public String getRCountry() {
        return this.RCountry;
    }
    
    public void setRCountry(String RCountry) {
        this.RCountry = RCountry;
    }
    public String getRPostalCode() {
        return this.RPostalCode;
    }
    
    public void setRPostalCode(String RPostalCode) {
        this.RPostalCode = RPostalCode;
    }
    public Long getRPhone() {
        return this.RPhone;
    }
    
    public void setRPhone(Long RPhone) {
        this.RPhone = RPhone;
    }
    public Long getRWorkPhone() {
        return this.RWorkPhone;
    }
    
    public void setRWorkPhone(Long RWorkPhone) {
        this.RWorkPhone = RWorkPhone;
    }
    public Long getRMobile() {
        return this.RMobile;
    }
    
    public void setRMobile(Long RMobile) {
        this.RMobile = RMobile;
    }
    public Long getRFax() {
        return this.RFax;
    }
    
    public void setRFax(Long RFax) {
        this.RFax = RFax;
    }
    public String getREmail() {
        return this.REmail;
    }
    
    public void setREmail(String REmail) {
        this.REmail = REmail;
    }
    public String getRContactOptions() {
        return this.RContactOptions;
    }
    
    public void setRContactOptions(String RContactOptions) {
        this.RContactOptions = RContactOptions;
    }
    public Date getRPostTime() {
        return this.RPostTime;
    }
    
    public void setRPostTime(Date RPostTime) {
        this.RPostTime = RPostTime;
    }




}


