package com.model;
// Generated Jul 27, 2012 5:21:52 PM by Hibernate Tools 3.2.1.GA



/**
 * Imagesfile generated by hbm2java
 */
public class Imagesfile  implements java.io.Serializable {


     private long id;
     private Sell sell;
     private byte[] img1;
     private byte[] img2;
     private byte[] img3;
     private byte[] img4;
     private byte[] img5;

    public Imagesfile() {
    }

	
    public Imagesfile(long id, Sell sell) {
        this.id = id;
        this.sell = sell;
    }
    public Imagesfile(long id, Sell sell, byte[] img1, byte[] img2, byte[] img3, byte[] img4, byte[] img5) {
       this.id = id;
       this.sell = sell;
       this.img1 = img1;
       this.img2 = img2;
       this.img3 = img3;
       this.img4 = img4;
       this.img5 = img5;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Sell getSell() {
        return this.sell;
    }
    
    public void setSell(Sell sell) {
        this.sell = sell;
    }
    public byte[] getImg1() {
        return this.img1;
    }
    
    public void setImg1(byte[] img1) {
        this.img1 = img1;
    }
    public byte[] getImg2() {
        return this.img2;
    }
    
    public void setImg2(byte[] img2) {
        this.img2 = img2;
    }
    public byte[] getImg3() {
        return this.img3;
    }
    
    public void setImg3(byte[] img3) {
        this.img3 = img3;
    }
    public byte[] getImg4() {
        return this.img4;
    }
    
    public void setImg4(byte[] img4) {
        this.img4 = img4;
    }
    public byte[] getImg5() {
        return this.img5;
    }
    
    public void setImg5(byte[] img5) {
        this.img5 = img5;
    }




}


