package com.model;
// Generated Jul 27, 2012 5:21:52 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Listings generated by hbm2java
 */
public class Listings  implements java.io.Serializable {


     private Long LId;
     private long reference;
     private String heading;
     private String summery;
     private String businessStatus;
     private String houseNo;
     private String road;
     private String region;
     private String town;
     private String country;
     private long postcode;
     private String businessClosed;
     private String relocatable;
     private String franchise;
     private String franchiseTerms;
     private String locationDetails;
     private String competition;
     private String potential;
     private String accomodation;
     private String accomDescription;
     private int yearsEstablished;
     private long employees;
     private String businessHours;
     private String supportTraining;
     private String sellReason;
     private long askingPrice;
     private long revenue;
     private long netProfit;
     private String fixtureFittings;
     private long fittingsValue;
     private String inventoryStock;
     private String financing;
     private String tenure;
     private String prefix;
     private String category;
     private Date advertisedDate;
     private String status;

    public Listings() {
    }

	
    public Listings(long reference, String heading, String summery, String businessStatus, String houseNo, String road, String region, String town, String country, long postcode, String relocatable, String franchise, String franchiseTerms, String locationDetails, String competition, String potential, String accomodation, String accomDescription, int yearsEstablished, long employees, String businessHours, String supportTraining, String sellReason, long askingPrice, long revenue, long netProfit, String fixtureFittings, long fittingsValue, String inventoryStock, String financing, String tenure, String prefix, String category, Date advertisedDate, String status) {
        this.reference = reference;
        this.heading = heading;
        this.summery = summery;
        this.businessStatus = businessStatus;
        this.houseNo = houseNo;
        this.road = road;
        this.region = region;
        this.town = town;
        this.country = country;
        this.postcode = postcode;
        this.relocatable = relocatable;
        this.franchise = franchise;
        this.franchiseTerms = franchiseTerms;
        this.locationDetails = locationDetails;
        this.competition = competition;
        this.potential = potential;
        this.accomodation = accomodation;
        this.accomDescription = accomDescription;
        this.yearsEstablished = yearsEstablished;
        this.employees = employees;
        this.businessHours = businessHours;
        this.supportTraining = supportTraining;
        this.sellReason = sellReason;
        this.askingPrice = askingPrice;
        this.revenue = revenue;
        this.netProfit = netProfit;
        this.fixtureFittings = fixtureFittings;
        this.fittingsValue = fittingsValue;
        this.inventoryStock = inventoryStock;
        this.financing = financing;
        this.tenure = tenure;
        this.prefix = prefix;
        this.category = category;
        this.advertisedDate = advertisedDate;
        this.status = status;
    }
    public Listings(long reference, String heading, String summery, String businessStatus, String houseNo, String road, String region, String town, String country, long postcode, String businessClosed, String relocatable, String franchise, String franchiseTerms, String locationDetails, String competition, String potential, String accomodation, String accomDescription, int yearsEstablished, long employees, String businessHours, String supportTraining, String sellReason, long askingPrice, long revenue, long netProfit, String fixtureFittings, long fittingsValue, String inventoryStock, String financing, String tenure, String prefix, String category, Date advertisedDate, String status) {
       this.reference = reference;
       this.heading = heading;
       this.summery = summery;
       this.businessStatus = businessStatus;
       this.houseNo = houseNo;
       this.road = road;
       this.region = region;
       this.town = town;
       this.country = country;
       this.postcode = postcode;
       this.businessClosed = businessClosed;
       this.relocatable = relocatable;
       this.franchise = franchise;
       this.franchiseTerms = franchiseTerms;
       this.locationDetails = locationDetails;
       this.competition = competition;
       this.potential = potential;
       this.accomodation = accomodation;
       this.accomDescription = accomDescription;
       this.yearsEstablished = yearsEstablished;
       this.employees = employees;
       this.businessHours = businessHours;
       this.supportTraining = supportTraining;
       this.sellReason = sellReason;
       this.askingPrice = askingPrice;
       this.revenue = revenue;
       this.netProfit = netProfit;
       this.fixtureFittings = fixtureFittings;
       this.fittingsValue = fittingsValue;
       this.inventoryStock = inventoryStock;
       this.financing = financing;
       this.tenure = tenure;
       this.prefix = prefix;
       this.category = category;
       this.advertisedDate = advertisedDate;
       this.status = status;
    }
   
    public Long getLId() {
        return this.LId;
    }
    
    public void setLId(Long LId) {
        this.LId = LId;
    }
    public long getReference() {
        return this.reference;
    }
    
    public void setReference(long reference) {
        this.reference = reference;
    }
    public String getHeading() {
        return this.heading;
    }
    
    public void setHeading(String heading) {
        this.heading = heading;
    }
    public String getSummery() {
        return this.summery;
    }
    
    public void setSummery(String summery) {
        this.summery = summery;
    }
    public String getBusinessStatus() {
        return this.businessStatus;
    }
    
    public void setBusinessStatus(String businessStatus) {
        this.businessStatus = businessStatus;
    }
    public String getHouseNo() {
        return this.houseNo;
    }
    
    public void setHouseNo(String houseNo) {
        this.houseNo = houseNo;
    }
    public String getRoad() {
        return this.road;
    }
    
    public void setRoad(String road) {
        this.road = road;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public String getTown() {
        return this.town;
    }
    
    public void setTown(String town) {
        this.town = town;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public long getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(long postcode) {
        this.postcode = postcode;
    }
    public String getBusinessClosed() {
        return this.businessClosed;
    }
    
    public void setBusinessClosed(String businessClosed) {
        this.businessClosed = businessClosed;
    }
    public String getRelocatable() {
        return this.relocatable;
    }
    
    public void setRelocatable(String relocatable) {
        this.relocatable = relocatable;
    }
    public String getFranchise() {
        return this.franchise;
    }
    
    public void setFranchise(String franchise) {
        this.franchise = franchise;
    }
    public String getFranchiseTerms() {
        return this.franchiseTerms;
    }
    
    public void setFranchiseTerms(String franchiseTerms) {
        this.franchiseTerms = franchiseTerms;
    }
    public String getLocationDetails() {
        return this.locationDetails;
    }
    
    public void setLocationDetails(String locationDetails) {
        this.locationDetails = locationDetails;
    }
    public String getCompetition() {
        return this.competition;
    }
    
    public void setCompetition(String competition) {
        this.competition = competition;
    }
    public String getPotential() {
        return this.potential;
    }
    
    public void setPotential(String potential) {
        this.potential = potential;
    }
    public String getAccomodation() {
        return this.accomodation;
    }
    
    public void setAccomodation(String accomodation) {
        this.accomodation = accomodation;
    }
    public String getAccomDescription() {
        return this.accomDescription;
    }
    
    public void setAccomDescription(String accomDescription) {
        this.accomDescription = accomDescription;
    }
    public int getYearsEstablished() {
        return this.yearsEstablished;
    }
    
    public void setYearsEstablished(int yearsEstablished) {
        this.yearsEstablished = yearsEstablished;
    }
    public long getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(long employees) {
        this.employees = employees;
    }
    public String getBusinessHours() {
        return this.businessHours;
    }
    
    public void setBusinessHours(String businessHours) {
        this.businessHours = businessHours;
    }
    public String getSupportTraining() {
        return this.supportTraining;
    }
    
    public void setSupportTraining(String supportTraining) {
        this.supportTraining = supportTraining;
    }
    public String getSellReason() {
        return this.sellReason;
    }
    
    public void setSellReason(String sellReason) {
        this.sellReason = sellReason;
    }
    public long getAskingPrice() {
        return this.askingPrice;
    }
    
    public void setAskingPrice(long askingPrice) {
        this.askingPrice = askingPrice;
    }
    public long getRevenue() {
        return this.revenue;
    }
    
    public void setRevenue(long revenue) {
        this.revenue = revenue;
    }
    public long getNetProfit() {
        return this.netProfit;
    }
    
    public void setNetProfit(long netProfit) {
        this.netProfit = netProfit;
    }
    public String getFixtureFittings() {
        return this.fixtureFittings;
    }
    
    public void setFixtureFittings(String fixtureFittings) {
        this.fixtureFittings = fixtureFittings;
    }
    public long getFittingsValue() {
        return this.fittingsValue;
    }
    
    public void setFittingsValue(long fittingsValue) {
        this.fittingsValue = fittingsValue;
    }
    public String getInventoryStock() {
        return this.inventoryStock;
    }
    
    public void setInventoryStock(String inventoryStock) {
        this.inventoryStock = inventoryStock;
    }
    public String getFinancing() {
        return this.financing;
    }
    
    public void setFinancing(String financing) {
        this.financing = financing;
    }
    public String getTenure() {
        return this.tenure;
    }
    
    public void setTenure(String tenure) {
        this.tenure = tenure;
    }
    public String getPrefix() {
        return this.prefix;
    }
    
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public Date getAdvertisedDate() {
        return this.advertisedDate;
    }
    
    public void setAdvertisedDate(Date advertisedDate) {
        this.advertisedDate = advertisedDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


