package com.model;
// Generated Jul 21, 2012 4:41:27 PM by Hibernate Tools 3.2.1.GA



/**
 * Mylists generated by hbm2java
 */
public class Mylists  implements java.io.Serializable {


     private Long LId;
     private String LTitle;
     private String LFirstName;
     private String LSurName;
     private String LCompanyName;
     private String LEmail;
     private Long LTelephone;
     private Long LWorkPhone;
     private Long LFax;
     private Long LMobile;
     private String LHouseNo;
     private String LRoad;
     private String LTown;
     private String LCountry;
     private Long LPostalcode;
     private String LRefList;
     private String LStatus;

    public Mylists() {
    }

	
    public Mylists(String LTitle, String LFirstName, String LSurName, String LEmail, String LHouseNo, String LRoad, String LTown, String LCountry, String LRefList, String LStatus) {
        this.LTitle = LTitle;
        this.LFirstName = LFirstName;
        this.LSurName = LSurName;
        this.LEmail = LEmail;
        this.LHouseNo = LHouseNo;
        this.LRoad = LRoad;
        this.LTown = LTown;
        this.LCountry = LCountry;
        this.LRefList = LRefList;
        this.LStatus = LStatus;
    }
    public Mylists(String LTitle, String LFirstName, String LSurName, String LCompanyName, String LEmail, Long LTelephone, Long LWorkPhone, Long LFax, Long LMobile, String LHouseNo, String LRoad, String LTown, String LCountry, Long LPostalcode, String LRefList, String LStatus) {
       this.LTitle = LTitle;
       this.LFirstName = LFirstName;
       this.LSurName = LSurName;
       this.LCompanyName = LCompanyName;
       this.LEmail = LEmail;
       this.LTelephone = LTelephone;
       this.LWorkPhone = LWorkPhone;
       this.LFax = LFax;
       this.LMobile = LMobile;
       this.LHouseNo = LHouseNo;
       this.LRoad = LRoad;
       this.LTown = LTown;
       this.LCountry = LCountry;
       this.LPostalcode = LPostalcode;
       this.LRefList = LRefList;
       this.LStatus = LStatus;
    }
   
    public Long getLId() {
        return this.LId;
    }
    
    public void setLId(Long LId) {
        this.LId = LId;
    }
    public String getLTitle() {
        return this.LTitle;
    }
    
    public void setLTitle(String LTitle) {
        this.LTitle = LTitle;
    }
    public String getLFirstName() {
        return this.LFirstName;
    }
    
    public void setLFirstName(String LFirstName) {
        this.LFirstName = LFirstName;
    }
    public String getLSurName() {
        return this.LSurName;
    }
    
    public void setLSurName(String LSurName) {
        this.LSurName = LSurName;
    }
    public String getLCompanyName() {
        return this.LCompanyName;
    }
    
    public void setLCompanyName(String LCompanyName) {
        this.LCompanyName = LCompanyName;
    }
    public String getLEmail() {
        return this.LEmail;
    }
    
    public void setLEmail(String LEmail) {
        this.LEmail = LEmail;
    }
    public Long getLTelephone() {
        return this.LTelephone;
    }
    
    public void setLTelephone(Long LTelephone) {
        this.LTelephone = LTelephone;
    }
    public Long getLWorkPhone() {
        return this.LWorkPhone;
    }
    
    public void setLWorkPhone(Long LWorkPhone) {
        this.LWorkPhone = LWorkPhone;
    }
    public Long getLFax() {
        return this.LFax;
    }
    
    public void setLFax(Long LFax) {
        this.LFax = LFax;
    }
    public Long getLMobile() {
        return this.LMobile;
    }
    
    public void setLMobile(Long LMobile) {
        this.LMobile = LMobile;
    }
    public String getLHouseNo() {
        return this.LHouseNo;
    }
    
    public void setLHouseNo(String LHouseNo) {
        this.LHouseNo = LHouseNo;
    }
    public String getLRoad() {
        return this.LRoad;
    }
    
    public void setLRoad(String LRoad) {
        this.LRoad = LRoad;
    }
    public String getLTown() {
        return this.LTown;
    }
    
    public void setLTown(String LTown) {
        this.LTown = LTown;
    }
    public String getLCountry() {
        return this.LCountry;
    }
    
    public void setLCountry(String LCountry) {
        this.LCountry = LCountry;
    }
    public Long getLPostalcode() {
        return this.LPostalcode;
    }
    
    public void setLPostalcode(Long LPostalcode) {
        this.LPostalcode = LPostalcode;
    }
    public String getLRefList() {
        return this.LRefList;
    }
    
    public void setLRefList(String LRefList) {
        this.LRefList = LRefList;
    }
    public String getLStatus() {
        return this.LStatus;
    }
    
    public void setLStatus(String LStatus) {
        this.LStatus = LStatus;
    }




}


