package com.model;
// Generated Jul 27, 2012 5:21:52 PM by Hibernate Tools 3.2.1.GA



/**
 * SampleMylist generated by hbm2java
 */
public class SampleMylist  implements java.io.Serializable {


     private Long mylistId;
     private String reference;
     private String heading;

    public SampleMylist() {
    }

    public SampleMylist(String reference, String heading) {
       this.reference = reference;
       this.heading = heading;
    }
   
    public Long getMylistId() {
        return this.mylistId;
    }
    
    public void setMylistId(Long mylistId) {
        this.mylistId = mylistId;
    }
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }
    public String getHeading() {
        return this.heading;
    }
    
    public void setHeading(String heading) {
        this.heading = heading;
    }




}


